'use client';

import { Bot, Pencil, Plus, ToggleLeft, Trash2, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { request, type Session } from '../lib/api';

type AiModel = { id: string; displayName: string; provider: 'DEEPSEEK' | 'OPENAI_COMPATIBLE'; model: string; baseUrl: string; isEnabled: boolean; hasApiKey: boolean };

export function SystemSettings({ session }: { session: Session }) {
  const [models, setModels] = useState<AiModel[]>([]); const [modal, setModal] = useState<AiModel | 'new' | null>(null); const [message, setMessage] = useState('');
  const load = () => request<AiModel[]>('/admin/ai-models', {}, session.accessToken).then(setModels).catch(error => setMessage(error instanceof Error ? error.message : '模型加载失败'));
  useEffect(() => { void load(); }, [session.accessToken]);
  const toggle = async (model: AiModel) => { try { const updated = await request<AiModel>(`/admin/ai-models/${model.id}/enabled`, { method: 'PATCH', body: JSON.stringify({ isEnabled: !model.isEnabled }) }, session.accessToken); setModels(items => items.map(item => item.id === model.id ? updated : item)); } catch (error) { setMessage(error instanceof Error ? error.message : '状态更新失败'); } };
  const remove = async (model: AiModel) => { if (!window.confirm(`确定删除「${model.displayName}」吗？`)) return; try { await request(`/admin/ai-models/${model.id}`, { method: 'DELETE' }, session.accessToken); setModels(items => items.filter(item => item.id !== model.id)); } catch (error) { setMessage(error instanceof Error ? error.message : '删除失败'); } };
  return <section className="system-settings"><h2>系统设置</h2><div className="system-tabs" role="tablist"><button className="active" role="tab" aria-selected="true"><Bot size={18}/>AI 模型管理</button></div><div className="model-head"><div><h3>已配置模型 <b>{models.length}</b></h3><p>添加后默认启用；学习助手会使用最早添加的启用模型。</p></div><button onClick={() => setModal('new')}><Plus size={18}/>添加模型</button></div>{message && <p className="form-error model-message">{message}</p>}{models.length ? <div className="model-list">{models.map(model => <article key={model.id}><div className="model-provider-mark">{model.provider === 'DEEPSEEK' ? 'DS' : 'AI'}</div><div className="model-copy"><strong>{model.displayName}</strong><span>{model.provider === 'DEEPSEEK' ? 'DeepSeek' : '自定义 OpenAI'} · {model.model}</span><small>{model.baseUrl}</small></div><span className={`model-status ${model.isEnabled ? 'enabled' : ''}`}>{model.isEnabled ? '已启用' : '已关闭'}</span><button className="model-toggle" onClick={() => void toggle(model)} aria-label={`${model.isEnabled ? '关闭' : '启用'} ${model.displayName}`}><ToggleLeft size={29}/></button><button className="model-icon-button" onClick={() => setModal(model)} aria-label={`编辑 ${model.displayName}`}><Pencil size={17}/></button><button className="model-icon-button danger" onClick={() => void remove(model)} aria-label={`删除 ${model.displayName}`}><Trash2 size={17}/></button></article>)}</div> : <div className="model-empty"><Bot size={28}/><strong>还没有配置模型</strong><p>添加 DeepSeek 或兼容 OpenAI Chat Completions 的模型开始使用。</p></div>}{modal && <AiModelDialog session={session} model={modal === 'new' ? null : modal} onClose={() => setModal(null)} onSaved={(model) => { setModels(items => items.some(item => item.id === model.id) ? items.map(item => item.id === model.id ? model : item) : [...items, model]); setModal(null); }}/>}</section>;
}

function AiModelDialog({ session, model, onClose, onSaved }: { session: Session; model: AiModel | null; onClose: () => void; onSaved: (model: AiModel) => void }) {
  const [provider, setProvider] = useState<AiModel['provider']>(model?.provider ?? 'DEEPSEEK'); const [displayName, setDisplayName] = useState(model?.displayName ?? ''); const [modelName, setModelName] = useState(model?.model ?? ''); const [baseUrl, setBaseUrl] = useState(model?.provider === 'OPENAI_COMPATIBLE' ? model.baseUrl : ''); const [apiKey, setApiKey] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!displayName.trim() || !modelName.trim() || (!model && !apiKey.trim()) || (provider === 'OPENAI_COMPATIBLE' && !baseUrl.trim())) return setMessage('请填写所有必填项。'); setBusy(true); setMessage(''); try { const payload = { displayName, provider, model: modelName, ...(provider === 'OPENAI_COMPATIBLE' ? { baseUrl } : {}), ...(apiKey ? { apiKey } : {}) }; const result = await request<AiModel>(model ? `/admin/ai-models/${model.id}` : '/admin/ai-models', { method: model ? 'PUT' : 'POST', body: JSON.stringify(payload) }, session.accessToken); onSaved(result); } catch (error) { setMessage(error instanceof Error ? error.message : '保存失败'); } finally { setBusy(false); } };
  return <div className="model-dialog-layer" role="dialog" aria-modal="true" aria-label={model ? '编辑模型' : '添加模型'}><button className="model-dialog-scrim" aria-label="关闭" onClick={onClose}/><form className="model-dialog" onSubmit={submit}><header><div><p>AI MODEL</p><h2>{model ? '编辑模型' : '添加模型'}</h2></div><button type="button" onClick={onClose} aria-label="关闭"><X size={22}/></button></header><div className="provider-choice" role="tablist"><button type="button" className={provider === 'DEEPSEEK' ? 'active' : ''} onClick={() => setProvider('DEEPSEEK')}>DeepSeek</button><button type="button" className={provider === 'OPENAI_COMPATIBLE' ? 'active' : ''} onClick={() => setProvider('OPENAI_COMPATIBLE')}>自定义 OpenAI</button></div><label>模型展示名称<input value={displayName} onChange={event => setDisplayName(event.target.value)} placeholder="例如：主学习助手" autoFocus/></label><label>模型 ID<input value={modelName} onChange={event => setModelName(event.target.value)} placeholder={provider === 'DEEPSEEK' ? 'deepseek-v4-flash' : '例如：gpt-4o-mini'}/></label>{provider === 'OPENAI_COMPATIBLE' && <label>API 地址<input value={baseUrl} onChange={event => setBaseUrl(event.target.value)} placeholder="https://api.example.com/v1"/></label>}<label>API 密钥{model?.hasApiKey && <small>留空则保持当前密钥</small>}<input type="password" value={apiKey} onChange={event => setApiKey(event.target.value)} placeholder={model?.hasApiKey ? '已配置' : '输入 API 密钥'} autoComplete="off"/></label>{message && <p className="form-error model-message">{message}</p>}<footer><button type="button" className="secondary" onClick={onClose}>取消</button><button disabled={busy}>{busy ? '保存中…' : model ? '保存修改' : '添加模型'}</button></footer></form></div>;
}
